spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/net365manager

logging:
  level:
    com.net365.manager: DEBUG
    org.springframework.data.mongodb: DEBUG
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
