spring:
  data:
    mongodb:
      uri: mongodb+srv://fabrizionegronquispe_db_user:gxpfVkS6TNSI14zh@cluster0.dlsx6dm.mongodb.net/net365manager?appName=Cluster0

logging:
  level:
    com.net365.manager: DEBUG
    org.springframework.data.mongodb: DEBUG
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
